export const practice: string;
export const practice_normal: string;
export const practice_compact: string;
export const practice_bare: string;
export const textInput: string;
export const textInput_normal: string;
export const textInput_compact: string;
export const textInput_bare: string;
export const keyboard: string;
