import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_DE_MINE: LayoutConfig = {
  codePoints: {
    Backquote: "^ˇ",
    Digit1: "1°",
    Digit2: "2§",
    Digit3: "3ℓ",
    Digit4: "4»",
    Digit5: "5«",
    Digit6: "6$",
    Digit7: "7€",
    Digit8: "8„",
    Digit9: "9“",
    Digit0: "0”",
    Minus: "-—",
    Equal: "`¸",
    KeyQ: "jJ",
    KeyW: "lL",
    KeyE: "uU",
    KeyR: "aA",
    KeyT: "qQ",
    KeyY: "wW",
    KeyU: "bB",
    KeyI: "dD",
    KeyO: "gG",
    KeyP: "YY",
    BracketLeft: "zZ",
    BracketRight: "ßẞ",
    Backslash: "",
    KeyA: "cC",
    KeyS: "rR",
    KeyD: "iI",
    KeyF: "eE",
    KeyG: "oO",
    KeyH: "mM",
    KeyJ: "nN",
    KeyK: "tT",
    KeyL: "sS",
    Semicolon: "hH",
    Quote: "",
    IntlBackslash: "´˜",
    KeyZ: "vV",
    KeyX: "xX",
    KeyC: "üÜ",
    KeyV: "äÄ",
    KeyB: "öÖ",
    KeyN: "pP",
    KeyM: "fF",
    Comma: ",–",
    Period: ".•",
    Slash: "kK",
    Space: "  ",
  },
};
