import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_EN_US_COLEMAK_DH_MATRIX: LayoutConfig = {
  codePoints: {
    Backquote: "`~",
    Digit1: "1!",
    Digit2: "2@",
    Digit3: "3#",
    Digit4: "4$",
    Digit5: "5%",
    Digit6: "6^",
    Digit7: "7&",
    Digit8: "8*",
    Digit9: "9(",
    Digit0: "0)",
    Minus: "-_",
    Equal: "=+",
    KeyQ: "qQ",
    KeyW: "wW",
    KeyE: "fF",
    KeyR: "pP",
    KeyT: "bB",
    KeyY: "jJ",
    KeyU: "lL",
    KeyI: "uU",
    KeyO: "yY",
    KeyP: ";:",
    BracketLeft: "[{",
    BracketRight: "]}",
    Backslash: "\\|",
    KeyA: "aA",
    KeyS: "rR",
    KeyD: "sS",
    KeyF: "tT",
    KeyG: "gG",
    KeyH: "mM",
    KeyJ: "nN",
    KeyK: "eE",
    KeyL: "iI",
    Semicolon: "oO",
    Quote: `'"`,
    IntlBackslash: "\\|",
    KeyZ: "zZ",
    KeyX: "xX",
    KeyC: "cC",
    KeyV: "dD",
    KeyB: "vV",
    KeyN: "kK",
    KeyM: "hH",
    Comma: ",<",
    Period: ".>",
    Slash: "/?",
    Space: " ",
  },
};
