import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_FR_ERGO_L: LayoutConfig = {
  codePoints: {
    Backquote: "`~",
    Digit1: "1!",
    Digit2: "2@",
    Digit3: "3#",
    Digit4: "4$",
    Digit5: "5%",
    Digit6: "6^",
    Digit7: "7&",
    Digit8: "8*",
    Digit9: "9(",
    Digit0: "0)",
    Minus: "-_",
    Equal: "=+",
    KeyQ: "qQ",
    KeyW: "cC",
    KeyE: "oO",
    KeyR: "pP",
    KeyT: "wW",
    KeyY: "jJ",
    KeyU: "mM",
    KeyI: "dD",
    KeyO: "`¨",
    KeyP: "fF",
    BracketLeft: "[{",
    BracketRight: "]}",
    Backslash: "\\|",
    KeyA: "aA",
    KeyS: "sS",
    KeyD: "eE",
    KeyF: "nN",
    KeyG: ",;",
    KeyH: "lL",
    KeyJ: "rR",
    KeyK: "tT",
    KeyL: "iI",
    Semicolon: "uU",
    Quote: `'"`,
    IntlBackslash: "\\|",
    KeyZ: "zZ",
    KeyX: "xX",
    KeyC: "-?",
    KeyV: "vV",
    KeyB: "bB",
    KeyN: ".:",
    KeyM: "hH",
    Comma: "gG",
    Period: "yY",
    Slash: "kK",
    Space: " ",
  },
};
