import { type LayoutConfig } from "../layout.ts";

export const LAYOUT_FR_OPTIMOT: LayoutConfig = {
  codePoints: {
    Backquote: ["$", "€", "£"],
    Digit1: ["«", "1", "“"],
    Digit2: ["»", "2", "”"],
    Digit3: ['"', "3", "„"],
    Digit4: ["-", "4"],
    Digit5: ["+", "5", "±"],
    Digit6: ["*", "6", "×"],
    Digit7: ["/", "7", "\\"],
    Digit8: ["=", "8", "≠"],
    Digit9: ["(", "9", "["],
    Digit0: [")", "0", "]"],
    Minus: ["@", "_"],
    Equal: ["#", "%", "°"],
    KeyQ: ["à", "À", "<", "≤"],
    KeyW: ["j", "J", ">", "≥"],
    KeyE: ["o", "O", "œ", "Œ"],
    KeyR: ["é", "É", "*´"],
    KeyT: ["b", "B", "—"],
    KeyY: ["f", "F"],
    KeyU: ["d", "D", "{"],
    KeyI: ["l", "L", "}"],
    KeyO: ["’", "?"],
    KeyP: ["q", "Q"],
    BracketLeft: ["x", "X", "|", "¦"],
    BracketRight: ["ç", "Ç"],
    KeyA: ["a", "A", "æ", "Æ"],
    KeyS: ["i", "I"],
    KeyD: ["e", "E"],
    KeyF: ["u", "U", "ù", "Ù"],
    KeyG: [",", ";", "–"],
    KeyH: ["p", "P"],
    KeyJ: ["t", "T", "&"],
    KeyK: ["s", "S"],
    KeyL: ["r", "R"],
    Semicolon: ["n", "N", "*~"],
    Quote: ["*^", "!", "*¨"],
    Backslash: ["z", "Z"],
    IntlBackslash: [], // TODO
    KeyZ: ["k", "K"],
    KeyX: ["y", "Y"],
    KeyC: ["è", "È", "*`"],
    KeyV: [".", ":", "…"],
    KeyB: ["w", "W", "•"],
    KeyN: ["g", "G"],
    KeyM: ["c", "C", "*¸"],
    Comma: ["m", "M"],
    Period: ["h", "H"],
    Slash: ["v", "V"],
    Space: [" ", 0x202f, "_", 0x00a0],
  },
};
