export const tabList: string;
export const item: string;
export const item_active: string;
export const item_inactive: string;
export const spacer: string;
export const spacer_middle: string;
export const spacer_first: string;
export const spacer_last: string;
export const disabled: string;
