import { CacheControl } from "@fastr/headers";

const assetsCacheControl = new CacheControl({
  isPublic: true,
  noTransform: true, // For Cloudflare, force it to serve compressed variants.
  maxAge: 31536000,
  ext: [["immutable", null]],
});

export const cacheControl = (path: string): CacheControl | null => {
  if (path.startsWith("/assets/")) {
    // Assets generated by Webpack.
    // These are immutable.
    return assetsCacheControl;
  }
  return null;
};
