import { makeAccessor } from "./input/ColorInput.tsx";

export const prop = {
  ["--textinput__color"]: makeAccessor("--textinput__color"),
  ["--textinput--special__color"]: makeAccessor("--textinput--special__color"),
  ["--textinput--hit__color"]: makeAccessor("--textinput--hit__color"),
  ["--textinput--miss__color"]: makeAccessor("--textinput--miss__color"),
  ["--slow-key-color"]: makeAccessor("--slow-key-color"),
  ["--fast-key-color"]: makeAccessor("--fast-key-color"),
  ["--effort-color"]: makeAccessor("--effort-color"),
  ["--Name-color"]: makeAccessor("--Name-color"),
  ["--Value-color"]: makeAccessor("--Value-color"),
  ["--Value--more__color"]: makeAccessor("--Value--more__color"),
  ["--Value--less__color"]: makeAccessor("--Value--less__color"),
  ["--Chart-speed__color"]: makeAccessor("--Chart-speed__color"),
  ["--Chart-accuracy__color"]: makeAccessor("--Chart-accuracy__color"),
  ["--Chart-complexity__color"]: makeAccessor("--Chart-complexity__color"),
  ["--Chart-threshold__color"]: makeAccessor("--Chart-threshold__color"),
  ["--Chart-hist-h__color"]: makeAccessor("--Chart-hist-h__color"),
  ["--Chart-hist-m__color"]: makeAccessor("--Chart-hist-m__color"),
  ["--Chart-hist-r__color"]: makeAccessor("--Chart-hist-r__color"),
  ["--pinky-zone-color"]: makeAccessor("--pinky-zone-color"),
  ["--ring-zone-color"]: makeAccessor("--ring-zone-color"),
  ["--middle-zone-color"]: makeAccessor("--middle-zone-color"),
  ["--left-index-zone-color"]: makeAccessor("--left-index-zone-color"),
  ["--right-index-zone-color"]: makeAccessor("--right-index-zone-color"),
  ["--thumb-zone-color"]: makeAccessor("--thumb-zone-color"),
  ["--syntax-keyword"]: makeAccessor("--syntax-keyword"),
  ["--syntax-number"]: makeAccessor("--syntax-number"),
  ["--syntax-string"]: makeAccessor("--syntax-string"),
  ["--syntax-comment"]: makeAccessor("--syntax-comment"),
} as const;
