// Generated file, do not edit.

import { type CharacterDict } from "../types.ts";

// prettier-ignore
export const LAYOUT_NE: CharacterDict = {
  Backquote: [/* DEVANAGARI LETTER NYA */ 0x091e, { ligature: "ञ्" }],
  Digit1: [{ ligature: "ज्ञ" }, /* DEVANAGARI DIGIT ONE */ 0x0967],
  Digit2: [/* DEVANAGARI LETTER GHA */ 0x0918, /* DEVANAGARI DIGIT TWO */ 0x0968],
  Digit3: [/* DEVANAGARI LETTER NGA */ 0x0919, /* DEVANAGARI DIGIT THREE */ 0x0969],
  Digit4: [/* DEVANAGARI LETTER JHA */ 0x091d, /* DEVANAGARI DIGIT FOUR */ 0x096a],
  Digit5: [/* DEVANAGARI LETTER CHA */ 0x091b, /* DEVANAGARI DIGIT FIVE */ 0x096b],
  Digit6: [/* DEVANAGARI LETTER TTA */ 0x091f, /* DEVANAGARI DIGIT SIX */ 0x096c],
  Digit7: [/* DEVANAGARI LETTER TTHA */ 0x0920, /* DEVANAGARI DIGIT SEVEN */ 0x096d],
  Digit8: [/* DEVANAGARI LETTER DDA */ 0x0921, /* DEVANAGARI DIGIT EIGHT */ 0x096e],
  Digit9: [/* DEVANAGARI LETTER DDHA */ 0x0922, /* DEVANAGARI DIGIT NINE */ 0x096f],
  Digit0: [/* DEVANAGARI LETTER NNA */ 0x0923, /* DEVANAGARI DIGIT ZERO */ 0x0966],
  Minus: [/* LEFT PARENTHESIS */ 0x0028, /* RIGHT PARENTHESIS */ 0x0029],
  Equal: [/* FULL STOP */ 0x002e, /* DEVANAGARI SIGN ANUSVARA */ 0x0902],
  KeyQ: [{ ligature: "त्र" }, /* DEVANAGARI VOWEL SIGN O */ 0x094b],
  KeyW: [/* DEVANAGARI LETTER DHA */ 0x0927, { ligature: "ध्" }],
  KeyE: [/* DEVANAGARI LETTER BHA */ 0x092d, { ligature: "भ्" }],
  KeyR: [/* DEVANAGARI LETTER CA */ 0x091a, { ligature: "च्" }],
  KeyT: [/* DEVANAGARI LETTER TA */ 0x0924, { ligature: "त्" }],
  KeyY: [/* DEVANAGARI LETTER THA */ 0x0925, { ligature: "थ्" }],
  KeyU: [/* DEVANAGARI LETTER GA */ 0x0917, { ligature: "ग्" }],
  KeyI: [/* DEVANAGARI LETTER SSA */ 0x0937, { ligature: "क्ष" }],
  KeyO: [/* DEVANAGARI LETTER YA */ 0x092f, /* DEVANAGARI LETTER I */ 0x0907],
  KeyP: [/* DEVANAGARI LETTER U */ 0x0909, /* DEVANAGARI LETTER E */ 0x090f],
  BracketLeft: [/* DEVANAGARI VOWEL SIGN VOCALIC R */ 0x0943, { ligature: "र्" }],
  BracketRight: [/* DEVANAGARI VOWEL SIGN E */ 0x0947, /* DEVANAGARI VOWEL SIGN AI */ 0x0948],
  Backslash: [{ ligature: "्र" }, /* DEVANAGARI SIGN VIRAMA */ 0x094d],
  KeyA: [/* DEVANAGARI LETTER BA */ 0x092c, { ligature: "ब्" }],
  KeyS: [/* DEVANAGARI LETTER KA */ 0x0915, { ligature: "क्" }],
  KeyD: [/* DEVANAGARI LETTER MA */ 0x092e, { ligature: "म्" }],
  KeyF: [/* DEVANAGARI VOWEL SIGN AA */ 0x093e, /* DEVANAGARI SIGN CANDRABINDU */ 0x0901],
  KeyG: [/* DEVANAGARI LETTER NA */ 0x0928, { ligature: "न्" }],
  KeyH: [/* DEVANAGARI LETTER JA */ 0x091c, { ligature: "ज्" }],
  KeyJ: [/* DEVANAGARI LETTER VA */ 0x0935, { ligature: "व्" }],
  KeyK: [/* DEVANAGARI LETTER PA */ 0x092a, { ligature: "प्" }],
  KeyL: [/* DEVANAGARI VOWEL SIGN I */ 0x093f, /* DEVANAGARI VOWEL SIGN II */ 0x0940],
  Semicolon: [/* DEVANAGARI LETTER SA */ 0x0938, { ligature: "स्" }],
  Quote: [/* DEVANAGARI VOWEL SIGN U */ 0x0941, /* DEVANAGARI VOWEL SIGN UU */ 0x0942],
  KeyZ: [/* DEVANAGARI LETTER SHA */ 0x0936, { ligature: "श्" }],
  KeyX: [/* DEVANAGARI LETTER HA */ 0x0939, { ligature: "ह्" }],
  KeyC: [/* DEVANAGARI LETTER A */ 0x0905, /* DEVANAGARI LETTER VOCALIC R */ 0x090b],
  KeyV: [/* DEVANAGARI LETTER KHA */ 0x0916, { ligature: "ख्" }],
  KeyB: [/* DEVANAGARI LETTER DA */ 0x0926, { ligature: "द्" }],
  KeyN: [/* DEVANAGARI LETTER LA */ 0x0932, { ligature: "ल्" }],
  KeyM: [/* DEVANAGARI LETTER PHA */ 0x092b, /* DEVANAGARI SIGN VISARGA */ 0x0903],
  Comma: [/* COMMA */ 0x002c, /* QUESTION MARK */ 0x003f],
  Period: [/* DEVANAGARI DANDA */ 0x0964, { ligature: "श्र" }],
  Slash: [/* DEVANAGARI LETTER RA */ 0x0930, { ligature: "रू" }],
  Space: [/* SPACE */ 0x0020],
};
