export const packageJsonKeys = [
  "private",
  "template",
  "name",
  "version",
  "type",
  "main",
  "types",
  "module",
  "browser",
  "exports",
  "imports",
  "sideEffects",
  ["dependencies", "alpha"],
  ["devDependencies", "alpha"],
  ["peerDependencies", "alpha"],
  ["optionalDependencies", "alpha"],
  ["scripts", ["clean", "compile", "test"]],
  ["ava", [["files", "alpha"], "extensions", "nodeArguments", "serial"]],
];

export const tsconfigJsonKeys = [
  "extends",
  [
    "compilerOptions",
    [
      "rootDir",
      "outDir",
      "lib",
      "declaration",
      "declarationMap",
      "noEmit",
      "emitDeclarationOnly",
      "incremental",
      "tsBuildInfoFile",
    ],
  ],
  ["include", "alpha"],
  ["exclude", "alpha"],
];
