export const legend_slow: string;
export const legend_fast: string;
export const legend_speed: string;
export const legend_accuracy: string;
export const legend_complexity: string;
export const legend_threshold: string;
export const legend_histogram_h: string;
export const legend_histogram_m: string;
export const legend_histogram_r: string;
