import { CacheControl } from "@fastr/headers";

const assetsCacheControl = new CacheControl({
  isPublic: true,
  noTransform: true, // Force Cloudflare to serve the compressed variants.
  maxAge: 31536000,
  ext: [["immutable", null]],
});

export const cacheControl = (path: string): CacheControl | null => {
  if (process.env.NODE_ENV === "development") {
    // Do not cache assets when running Webpack in the watch mode.
    return new CacheControl({ isPrivate: true, noStore: true, maxAge: 0 });
  }
  if (path.startsWith("/assets/")) {
    // Assets generated by Webpack for the production env are immutable.
    return assetsCacheControl;
  }
  return null;
};
