export const sizeFit: string;
export const sizeFill: string;
export const sizeFillAlt: string;
export const sizeFull: string;
export const width10: string;
export const width16: string;
export const width24: string;
export const width32: string;
export const widthFull: string;
