export const sizeFit: string;
export const sizeFill: string;
export const sizeFillAlt: string;
export const sizeFull: string;
export const widthNormal: string;
export const widthWide: string;
export const widthExtraWide: string;
export const widthExtraExtraWide: string;
export const widthFull: string;
